services:
  slogos-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: slogos-dev
    ports:
      - "5006:5000"
      - "35729:35729"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: npm run dev
